import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import { ethers } from "ethers";

const Home: NextPage = () => {
  const [errorMessage, setErrorMessage] = useState('');
  const [account, setAccount] = useState('');
  const [balance, setBalance] = useState('');

  useEffect(() => {
    if (window.ethereum) {
      window.ethereum.on("accountsChanged", accountsChanged);
      window.ethereum.on("chainChanged", chainChanged);
    }
  }, []);

  const connectWallet = async () => {
    if (window.ethereum) {
      try {
        const res = await window.ethereum.request({
          method: "eth_requestAccounts",
        });
        await accountsChanged(res[0]);
      } catch (err) {
        console.error(err);
        setErrorMessage("There was a problem connecting to MetaMask");
      }
    } else {
      setErrorMessage("Install MetaMask");
    }
  };

  const accountsChanged = async (newAccount) => {
    setAccount(newAccount);
    try {
      const balance = await window.ethereum.request({
        method: "eth_getBalance",
        params: [newAccount.toString(), "latest"],
      });
      setBalance(ethers.utils.formatEther(balance));
    } catch (err) {
      console.error(err);
      setErrorMessage("There was a problem connecting to MetaMask");
    }
  };

  const chainChanged = () => {
    setErrorMessage('');
    setAccount('');
    setBalance('');
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="/">Ice Cream Voting!</a>
        </h1>

        <button type="button" onClick={connectWallet}>
          Connect Wallet!
        </button>
        <p>Account: {account}</p>
        <p>
          Balance: {balance} {balance ? "ETH" : null}
        </p>
        {errorMessage ? <div color="red">Error: {errorMessage}</div> : null}

        {account ? <button type="button">Purchase Tokens</button> : null }
      </main>
    </div>
  );
};

export default Home;
